version: '3.3'
services:
  nginx:
    build:
      context: ../../dockerfiles/nginx
      dockerfile: Dockerfile
    command: sh /home/scripts/start.sh
    volumes:
      - ../nginx/nginx_config_cert.conf:/etc/nginx/conf.d/default.conf
      - ../../cert:/etc/letsencrypt
    ports:
      - 80:80